# Generated by Django 5.0.1 on 2024-01-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(default='Новый', max_length=255),
        ),
    ]
