# Generated by Django 5.0.1 on 2024-01-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
