# Generated by Django 5.0.1 on 2024-01-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team/', verbose_name='фото')),
                ('name', models.CharField(max_length=355, verbose_name='имя')),
                ('disc', models.TextField(verbose_name='описание')),
                ('phone', models.CharField(max_length=255, verbose_name='номер телефона')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
