# Generated by Django 5.0.1 on 2024-01-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=244, verbose_name='Название сайта')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='логотип')),
                ('disc', models.TextField(verbose_name='Описание')),
                ('number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Url Twitter')),
                ('Facebook', models.URLField(blank=True, null=True, verbose_name='Url Facebook')),
                ('Instagram', models.URLField(blank=True, null=True, verbose_name='Url instagram')),
            ],
            options={
                'verbose_name': 'Основные настройки',
                'verbose_name_plural': 'Основные настройки',
            },
        ),
    ]
