# Generated by Django 5.0.1 on 2024-01-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='client_logo', verbose_name='фото')),
                ('disc', models.TextField(verbose_name='Отзыв')),
            ],
        ),
    ]
