# Generated by Django 5.0.1 on 2024-01-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзавы'},
        ),
    ]
