# Generated by Django 5.0.1 on 2024-01-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='addres',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
