# Generated by Django 5.0.1 on 2024-01-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='message',
            field=models.DateTimeField(auto_now_add=True, verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='номер телофена'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='sabject',
            field=models.CharField(max_length=100, verbose_name='Услуга'),
        ),
    ]
